# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hi, I'm Linkun Lei
# Description of the Site
description: Cornell MFE Student | Chinese | Big Soccer Fan | ESTJ | Looking for a Full-time Job
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ll2229@cornell.edu
instagram_username: Linkun lei
linkedin_username: Linkun Lei
github_username:  Llk0510


# Name of the Author
author-name: Linkun Lei
# URL for the Image of the Author
author-image: /assets/images/雷林琨证件照.jpg
# 60 Words About the Author
author-about: Hi, my name is Linkun Lei, and I am currently pursuing a Master degree in Financial Engineering at Cornell University. I completed my undergraduate degree from Wuhan University in China with a major in Automation and a minor in Finance .Outside of academic, I have solid experience in quantitative research and trading. During my internship at Changjiang Securities, I improved ETF sector rotation strategies by boosting processing speed. At AEGON-Industrial Fund, I designed a multi-factor strategy that achieved a 30% annualized return in back-testing. Additionally, I conducted equity research at China Securities, producing on-site market research and in-depth reports .


# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: posts
    values:
      permalink: /blog/:title/
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
